/* Generated by make-facts.js. Verified data shared by every v11 version. Do not edit by hand. */
window.FACTS = {
 "readDate": "29 September 2026",
 "readNote": "View counts and runtimes read from YouTube page data on 29 September 2026. No video was played.",
 "brand": "Talex Media",
 "founderQuote": {
  "text": "If you stripped your name and your product off this piece of content, would anyone still want to watch it?",
  "who": "Tom Langan, founder of Talex Media",
  "article": "What's 100 Years Old is New Again",
  "date": "22 May 2026",
  "url": "https://www.linkedin.com/pulse/whats-100-years-old-new-again-tom-langan-6bm2e"
 },
 "rounds": [
  {
   "n": 1,
   "id": "repetition",
   "rung": "Repetition",
   "lesson": "A series gives people a reason to come back. A single film does not.",
   "company": "P&G",
   "winner": "ricos",
   "sides": {
    "ricos": {
     "key": "ricos",
     "name": "Rico's Tacos, the series",
     "videoId": "PeUsXJ4ccXY",
     "videoLabel": "Rico's Tacos, Episode 1: Flavor Has a Price",
     "channel": "MinivelaTV",
     "views": 200590,
     "seconds": 70,
     "youtubeTitle": "Rico's Tacos Episode 1: Flavor Has a Price",
     "kind": "series",
     "label": "A scripted comedy series in 22 short episodes",
     "channelOwner": "MinivelaTV, the channel of Minivela, which makes Rico's Tacos with P&G and Albertsons Media Collective",
     "firstEpisodeViews": 200590,
     "totalViews": 1305638,
     "episodes": 22,
     "runDates": "23 June to 28 August 2026",
     "cadence": "about twice a week"
    },
    "tideSpot": {
     "key": "tideSpot",
     "name": "School Lunch, the Tide commercial",
     "videoId": "xPHs8yT8cPM",
     "videoLabel": "Tide, School Lunch",
     "channel": "Tide",
     "views": 28887,
     "seconds": 30,
     "youtubeTitle": "Tide | School Lunch",
     "kind": "commercial",
     "label": "A thirty-second Tide commercial",
     "channelOwner": "Tide",
     "published": "15 October 2025"
    }
   },
   "episodes": [
    {
     "ep": 1,
     "title": "Flavor Has a Price",
     "id": "PeUsXJ4ccXY",
     "views": 200590,
     "seconds": 70,
     "published": "20260623"
    },
    {
     "ep": 2,
     "title": "Ketchup Guy",
     "id": "6o8qyAtE_kw",
     "views": 39987,
     "seconds": 98,
     "published": "20260626"
    },
    {
     "ep": 3,
     "title": "Abuela's Inspection",
     "id": "eqrcwwleJ0k",
     "views": 67561,
     "seconds": 93,
     "published": "20260630"
    },
    {
     "ep": 4,
     "title": "Influencer Taco",
     "id": "NrDDMWTo7zg",
     "views": 65864,
     "seconds": 67,
     "published": "20260703"
    },
    {
     "ep": 5,
     "title": "Fusion Tacos",
     "id": "nlf7rBo7sS8",
     "views": 65706,
     "seconds": 61,
     "published": "20260707"
    },
    {
     "ep": 6,
     "title": "Three Mariachis",
     "id": "O5916kbZip0",
     "views": 68292,
     "seconds": 92,
     "published": "20260707"
    },
    {
     "ep": 7,
     "title": "First Date Taco Friday",
     "id": "4WvJvqHReBw",
     "views": 67108,
     "seconds": 72,
     "published": "20260710"
    },
    {
     "ep": 8,
     "title": "The Ex-Girlfriend",
     "id": "eqknl8Xtpm0",
     "views": 68046,
     "seconds": 128,
     "published": "20260714"
    },
    {
     "ep": 9,
     "title": "Taco Tuesday Fiasco",
     "id": "tXvZGK1uKLk",
     "views": 1084,
     "seconds": 148,
     "published": "20260714"
    },
    {
     "ep": 10,
     "title": "Rico's Day Off",
     "id": "C0KqsKhjVuA",
     "views": 83,
     "seconds": 99,
     "published": "20260717"
    },
    {
     "ep": 11,
     "title": "Taco Negotiator",
     "id": "Pr_5XVNZjWE",
     "views": 50063,
     "seconds": 64,
     "published": "20260721"
    },
    {
     "ep": 12,
     "title": "Carnivore Taco Challenge",
     "id": "sGoFKcKD4nE",
     "views": 49595,
     "seconds": 104,
     "published": "20260724"
    },
    {
     "ep": 13,
     "title": "Taco Diet",
     "id": "t_XQJst-NQk",
     "views": 50267,
     "seconds": 83,
     "published": "20260728"
    },
    {
     "ep": 14,
     "title": "My Taco, My Way",
     "id": "cAOaEA9tltI",
     "views": 51001,
     "seconds": 95,
     "published": "20260731"
    },
    {
     "ep": 15,
     "title": "Taycos, Tacos",
     "id": "bPj1ZLf8T-c",
     "views": 52692,
     "seconds": 113,
     "published": "20260804"
    },
    {
     "ep": 16,
     "title": "The Startup Guy",
     "id": "tvJx5hMpnwM",
     "views": 54918,
     "seconds": 49,
     "published": "20260807"
    },
    {
     "ep": 16,
     "title": "Taco Enlightenment",
     "id": "luZXnzjwwag",
     "views": 57700,
     "seconds": 99,
     "published": "20260811"
    },
    {
     "ep": 17,
     "title": "Livestream Taco",
     "id": "cHCfALYUyuI",
     "views": 56538,
     "seconds": 81,
     "published": "20260814"
    },
    {
     "ep": 18,
     "title": "Dessert Taco",
     "id": "XUYcHgSFjsk",
     "views": 59355,
     "seconds": 79,
     "published": "20260818"
    },
    {
     "ep": 19,
     "title": "Truth-Teller Taco",
     "id": "fQsHw7k_r24",
     "views": 63165,
     "seconds": 103,
     "published": "20260821"
    },
    {
     "ep": 20,
     "title": "Ultimate Taco",
     "id": "MfgIQ8qedFI",
     "views": 58529,
     "seconds": 131,
     "published": "20260825"
    },
    {
     "ep": 21,
     "title": "Taco-versary",
     "id": "bqi_UTafTpM",
     "views": 57494,
     "seconds": 133,
     "published": "20260828"
    }
   ],
   "episodeNote": "Two episodes are numbered 16. Episodes 9 and 10 show far fewer views than every other episode.",
   "measure": "views",
   "why": {
    "question": "Both are P&G. Why did the series get more views?",
    "options": [
     {
      "side": "ricos",
      "text": "A series gives people a reason to come back."
     },
     {
      "side": "tideSpot",
      "text": "One film can run everywhere at once, so it reaches more people."
     },
     {
      "side": "tideSpot",
      "text": "One polished film costs far less to make than twenty-two episodes."
     }
    ]
   },
   "quote": {
    "text": "You need it to be episodic, because a series earns you a return visit and a one off never does.",
    "cite": "Tom Langan, Welcome to The Taco Drama, 30 July 2026",
    "url": "https://www.linkedin.com/pulse/welcome-taco-drama-tom-langan-wusce"
   }
  },
  {
   "n": 2,
   "id": "cast",
   "rung": "A cast people come back for",
   "lesson": "Coming back is not enough on its own, and a line that repeats is not the same as a cast that returns. People grow fond of a cast and come back to see what situation those people are in next. A new cast every time, however familiar the line, gives an audience nobody to grow fond of.",
   "company": "Allstate",
   "winner": "mayhem",
   "sides": {
    "mayhem": {
     "key": "mayhem",
     "name": "Mayhem",
     "videoId": "InPoTHIrnp0",
     "videoLabel": "Mayhem: Action Hero, an Allstate commercial",
     "channel": "Allstate",
     "views": 106185,
     "seconds": 60,
     "youtubeTitle": "Mayhem Action Hero :60",
     "kind": "commercial",
     "label": "Mayhem, one character since 2010, played by Dean Winters",
     "channelOwner": "Allstate"
    },
    "checkFirst": {
     "key": "checkFirst",
     "name": "Check First, Swim Meet",
     "videoId": "I6QksAqf0jk",
     "videoLabel": "Allstate Check First, Swim Meet",
     "channel": "Allstate",
     "views": 6183,
     "seconds": 30,
     "youtubeTitle": "Allstate Check First Swim Meet :30",
     "kind": "commercial",
     "label": "Check First, a new cast in every spot",
     "channelOwner": "Allstate",
     "published": "3 September 2026",
     "campaignSpots": [
      "Swim Meet",
      "Superstitious",
      "Outfit"
     ],
     "repeatedLine": "Check Allstate first.",
     "evidence": "Allstate's YouTube channel carries three Check First commercials, each with a different cast, and YouTube captions show every one says \"check Allstate first.\""
    }
   },
   "evidence": [
    {
     "stat": "#1",
     "label": "Most memorable ads among insurance mascots",
     "source": "MarketCast, January 2024 to February 2025, via MarTech Edge, 1 April 2025",
     "url": "https://martechedge.com/news/liberty-mutuals-limu-emu-leads-the-pack-in-insurance-mascot-performance-marketcast-finds"
    },
    {
     "stat": "+8%",
     "label": "Likeability above the norm",
     "source": "MarketCast via MarTech Edge, 1 April 2025",
     "url": "https://martechedge.com/news/liberty-mutuals-limu-emu-leads-the-pack-in-insurance-mascot-performance-marketcast-finds"
    },
    {
     "stat": "31%",
     "label": "picked Mayhem as the mascot they would most like to grab a beer with, second only to Jake from State Farm at 34%",
     "source": "Insurity online survey of more than 1,000 US adults, January 2024, via Business Wire, 7 March 2024",
     "url": "https://www.businesswire.com/news/home/20240307812926/en/Insurity-Survey-Reveals-Americas-Most-Beloved-PC-Insurance-Mascots-Amidst-Billion-Dollar-Advertising-Efforts"
    }
   ],
   "evidenceScope": "Both studies rank Mayhem against other insurers' mascots. No published study compares Mayhem with Check First.",
   "viewsAreNotEvidence": "Do not use YouTube views as evidence in this round. Commercial view counts on a brand channel mostly reflect paid promotion; the measure is the mascot research.",
   "measure": "which one people remember",
   "why": {
    "question": "Allstate makes both. Why do people remember Mayhem?",
    "options": [
     {
      "side": "checkFirst",
      "text": "A fresh cast in every spot keeps a campaign from going stale."
     },
     {
      "side": "mayhem",
      "text": "People have grown fond of Mayhem, so each new spot is a chance to see what situation he is in next."
     },
     {
      "side": "checkFirst",
      "text": "Repeating one line in every spot gives people as much to hold on to as one character does."
     }
    ]
   },
   "quote": {
    "text": "MarketCast put Mayhem first among insurance mascots for likeability and for the most memorable ads. A separate Insurity survey of more than 1,000 US adults asked which mascot they would most like to grab a beer with. 31 percent picked Mayhem, second only to Jake from State Farm at 34 percent.",
    "cite": "MarketCast via MarTech Edge, 1 April 2025, and Insurity via Business Wire, 7 March 2024",
    "url": "https://martechedge.com/news/liberty-mutuals-limu-emu-leads-the-pack-in-insurance-mascot-performance-marketcast-finds"
   }
  },
  {
   "n": 3,
   "id": "audience",
   "rung": "Made for the audience, not about the brand",
   "lesson": "People return for something they want to watch, not for something about the product.",
   "company": "Red Bull",
   "winner": "stratos",
   "sides": {
    "stratos": {
     "key": "stratos",
     "name": "Stratos, the jump",
     "videoId": "FHtvDA0W34I",
     "videoLabel": "Felix Baumgartner's supersonic freefall from 128k', Mission Highlights",
     "channel": "Red Bull",
     "views": 49057113,
     "seconds": 90,
     "youtubeTitle": "Felix Baumgartner's supersonic freefall from 128k' - Mission Highlights",
     "kind": "live event",
     "label": "A live jump from the edge of space, streamed free on YouTube",
     "channelOwner": "Red Bull",
     "published": "15 October 2012",
     "concurrentStreams": "more than 8 million concurrent livestreams at the peak, the most of any livestream on YouTube at the time",
     "concurrentSource": "YouTube official blog, 14 October 2012",
     "concurrentUrl": "https://blog.youtube/news-and-events/mission-complete-red-bull-stratos-lands/"
    },
    "confession": {
     "key": "confession",
     "name": "Confession, the cartoon",
     "videoId": "0b3OPo9wHuk",
     "videoLabel": "Confession, a 2011 Red Bull cartoon advert",
     "channel": "Red Bull",
     "views": 252155,
     "seconds": 30,
     "youtubeTitle": "\"Confession\" - 2011 Red Bull Cartoon Ad",
     "kind": "commercial",
     "label": "A thirty-second Gives You Wiiings cartoon",
     "channelOwner": "Red Bull",
     "published": "26 January 2011",
     "cartoonsSince": 1989,
     "cartoonsSource": "Kunstmeile Krems exhibition \"Gives You Wings. 30 Years of Cartoons by Red Bull\", 2017"
    }
   },
   "sameChannel": true,
   "measure": "views",
   "why": {
    "question": "Both films are Red Bull, on the same channel. Why did the jump get nearly two hundred times the views?",
    "options": [
     {
      "side": "stratos",
      "text": "The jump was something people wanted to watch for its own sake, and Red Bull gave it away free with nothing asked in return."
     },
     {
      "side": "confession",
      "text": "A thirty-second cartoon costs little enough to run all year."
     },
     {
      "side": "confession",
      "text": "Putting the product on screen is what turns attention into sales."
     }
    ]
   },
   "quote": {
    "text": "They didn't gate it behind a sign-up. They didn't cut away to a guy chugging a can the second Felix landed.",
    "cite": "Tom Langan, Where the Rubber Meets The Restaurant, 10 June 2026",
    "url": "https://www.linkedin.com/pulse/where-rubber-meets-restaurant-tom-langan-gllme"
   }
  },
  {
   "n": 4,
   "id": "ownership",
   "rung": "Own the show",
   "lesson": "When you own the show, the audience is yours, not rented.",
   "company": "YETI",
   "winner": "yetiFilm",
   "sides": {
    "yetiFilm": {
     "key": "yetiFilm",
     "name": "A Thousand Casts, the YETI Presents film",
     "videoId": "OmrufRLGdAk",
     "videoLabel": "YETI Presents, A Thousand Casts",
     "channel": "YETI",
     "views": 1384277,
     "seconds": 1709,
     "youtubeTitle": "YETI Presents | A Thousand Casts | Oliver White's once-in-a-lifetime fly fishing trip to Bhutan",
     "kind": "documentary",
     "label": "A YETI Presents documentary on YETI's own channel",
     "channelOwner": "YETI",
     "published": "15 August 2023",
     "seriesSince": 2015
    },
    "pbrSponsor": {
     "key": "pbrSponsor",
     "name": "YETI's PBR sponsorship",
     "videoId": "6ti-Ky0zYhA",
     "videoLabel": "2026 PBR YETI Bucking Bull Champion Ransom",
     "channel": "PBR",
     "views": 13965,
     "seconds": 450,
     "youtubeTitle": "2026 PBR YETI Bucking Bull Champion Ransom",
     "kind": "sponsorship",
     "label": "YETI's name on a PBR bull riding award, inside PBR's coverage",
     "channelOwner": "PBR (Professional Bull Riders)",
     "published": "17 May 2026",
     "sponsorSince": 2017,
     "sponsorNote": "YETI first sponsored PBR in 2013; the deal lapsed and resumed in 2017 (Front Office Sports, October 2019)"
    }
   },
   "measure": "which one did more for YETI",
   "why": {
    "question": "Both are YETI. Why does the film do more for YETI in the long run?",
    "options": [
     {
      "side": "yetiFilm",
      "text": "The film sits on a channel YETI owns, so the audience the film brings in is YETI's to keep."
     },
     {
      "side": "pbrSponsor",
      "text": "A sponsorship puts the name in front of a crowd that has already gathered."
     },
     {
      "side": "pbrSponsor",
      "text": "Naming an award costs less than producing a documentary."
     }
    ]
   },
   "quote": {
    "text": "PBR makes the film about its award and owns the channel that film sits on. YETI makes A Thousand Casts and owns the channel that film sits on.",
    "cite": "PBR, 17 May 2026, and YETI, 15 August 2023",
    "url": "https://www.youtube.com/watch?v=6ti-Ky0zYhA"
   }
  }
 ],
 "synthesis": [
  "A series gives people a reason to come back. A single film does not.",
  "Coming back is not enough on its own, and a line that repeats is not the same as a cast that returns. People grow fond of a cast and come back to see what situation those people are in next. A new cast every time, however familiar the line, gives an audience nobody to grow fond of.",
  "People return for something they want to watch, not for something about the product.",
  "When you own the show, the audience is yours, not rented."
 ],
 "closingQuestion": "Could your company make a show that comes back every week or every month, with a format and a cast your audience gets to know? Could you make that show for your audience rather than about your company, and own it rather than rent space in somebody else's show?",
 "cta": {
  "heading": "Do you have the team to make it?",
  "copy": "If you have the idea but not the team to make it, Talex is the team.",
  "button": "Book A Call With Our Team",
  "url": "https://calendly.com/talextom/20-min-discovery-call"
 },
 "principles": [
  "Consistency Is Key",
  "It's Not About You. It's About Them.",
  "Give Without Expectation"
 ],
 "evansCopyDecisions": {
  "title": "Which One Was Better?",
  "lead": "In each round, watch two case studies of video content from the same company, then pick which one is better and why.",
  "noticeAboutNumbers": "Watch each film right here. View counts come straight from YouTube, and every other figure names its source.",
  "correctPick": "Correct.",
  "correctReason": "You are correct.",
  "pickInstruction": "Choose the one you think worked best.",
  "readMore": "Read more about {subject}",
  "founderCredit": "Quote from Talex Media Founder, Tom Langan, in his article \"What's 100 Years Old is New Again\", 22 May 2026",
  "founderLink": "Read the article",
  "keep": [
   "Do you have the team to make it?",
   "It's Not About You. It's About Them."
  ],
  "dislikes": [
   "\"You called it\" and \"called it\" (use \"Correct\")",
   "black pill boxes / chips",
   "research-note tone such as \"we checked\", \"none found\", \"views read on\"",
   "all-caps credits",
   "\"draft for Tom\""
  ]
 }
};
